namespace Dhcp
{
    internal enum DhcpOption
    {
        /// <summary>Option 1</summary>
        SubnetMask = 0x1,
        /// <summary>Option 2</summary>
        TimeOffset = 0x2,
        /// <summary>Option 3</summary>
        Router = 0x3,
        /// <summary>Option 4</summary>
        TimeServer = 0x4,
        /// <summary>Option 5</summary>
        NameServer = 0x5,
        /// <summary>Option 6</summary>
        DomainNameServers = 0x6,
        /// <summary>Option 7</summary>
        LogServer = 0x7,
        /// <summary>Option 8</summary>
        CookieServer = 0x8,
        /// <summary>Option 9</summary>
        LPRServer = 0x9,
        /// <summary>Option 10</summary>
        ImpressServer = 0xA,
        /// <summary>Option 11</summary>
        ResourceLocServer = 0xB,
        /// <summary>Option 12</summary>
        HostName = 0xC,
        /// <summary>Option 13</summary>
        BootFileSize = 0xD,
        /// <summary>Option 14</summary>
        MeritDump = 0xE,
        /// <summary>Option 15</summary>
        DomainName = 0xF,
        /// <summary>Option 16</summary>
        SwapServer = 0x10,
        /// <summary>Option 17</summary>
        RootPath = 0x11,
        /// <summary>Option 18</summary>
        ExtensionsPath = 0x12,
        /// <summary>Option 19</summary>
        IpForwarding = 0x13,
        /// <summary>Option 20</summary>
        NonLocalSourceRouting = 0x14,
        /// <summary>Option 21</summary>
        PolicyFilter = 0x15,
        /// <summary>Option 22</summary>
        MaximumDatagramReAssemblySize = 0x16,
        /// <summary>Option 23</summary>
        DefaultIPTimeToLive = 0x17,
        /// <summary>Option 24</summary>
        PathMTUAgingTimeout = 0x18,
        /// <summary>Option 25</summary>
        PathMTUPlateauTable = 0x19,
        /// <summary>Option 26</summary>
        InterfaceMTU = 0x1A,
        /// <summary>Option 27</summary>
        AllSubnetsAreLocal = 0x1B,
        /// <summary>Option 28</summary>
        BroadcastAddress = 0x1C,
        /// <summary>Option 29</summary>
        PerformMaskDiscovery = 0x1D,
        /// <summary>Option 30</summary>
        MaskSupplier = 0x1E,
        /// <summary>Option 31</summary>
        PerformRouterDiscovery = 0x1F,
        /// <summary>Option 32</summary>
        RouterSolicitationAddress = 0x20,
        /// <summary>Option 33</summary>
        StaticRoute = 0x21,
        /// <summary>Option 34</summary>
        TrailerEncapsulation = 0x22,
        /// <summary>Option 35</summary>
        ARPCacheTimeout = 0x23,
        /// <summary>Option 36</summary>
        EthernetEncapsulation = 0x24,
        /// <summary>Option 37</summary>
        TCPDefaultTTL = 0x25,
        /// <summary>Option 38</summary>
        TCPKeepaliveInterval = 0x26,
        /// <summary>Option 39</summary>
        TCPKeepaliveGarbage = 0x27,
        /// <summary>Option 40</summary>
        NetworkInformationServiceDomain = 0x28,
        /// <summary>Option 41</summary>
        NetworkInformationServers = 0x29,
        /// <summary>Option 42</summary>
        NetworkTimeProtocolServers = 0x2A,
        /// <summary>Option 43</summary>
        VendorSpecificInformation = 0x2B,
        /// <summary>Option 44</summary>
        NetBIOSoverTCPIPNameServer = 0x2C,
        /// <summary>Option 45</summary>
        NetBIOSoverTCPIPDatagramDistributionServer = 0x2D,
        /// <summary>Option 46</summary>
        NetBIOSoverTCPIPNodeType = 0x2E,
        /// <summary>Option 47</summary>
        NetBIOSoverTCPIPScope = 0x2F,
        /// <summary>Option 48</summary>
        XWindowSystemFontServer = 0x30,
        /// <summary>Option 49</summary>
        XWindowSystemDisplayManager = 0x31,
        /// <summary>Option 50</summary>
        RequestedIPAddress = 0x32,
        /// <summary>Option 51</summary>
        IPAddressLeaseTime = 0x33,
        /// <summary>Option 52</summary>
        OptionOverload = 0x34,
        /// <summary>Option 53</summary>
        DHCPMessageTYPE = 0x35,
        /// <summary>Option 54</summary>
        ServerIdentifier = 0x36,
        /// <summary>Option 55</summary>
        ParameterRequestList = 0x37,
        /// <summary>Option 56</summary>
        Message = 0x38,
        /// <summary>Option 57</summary>
        MaximumDHCPMessageSize = 0x39,
        /// <summary>Option 58</summary>
        RenewalTimeValue_T1 = 0x3A,
        /// <summary>Option 59</summary>
        RebindingTimeValue_T2 = 0x3B,
        /// <summary>Option 60</summary>
        Vendorclassidentifier = 0x3C,
        /// <summary>Option 61</summary>
        ClientIdentifier = 0x3D,
        /// <summary>Option 62</summary>
        NetWateIPDomainName = 0x3E,
        /// <summary>Option 63</summary>
        NetWateIPInformation = 0x3F,
        /// <summary>Option 64</summary>
        NetworkInformationServicePlusDomain = 0x40,
        /// <summary>Option 65</summary>
        NetworkInformationServicePlusServers = 0x41,
        /// <summary>Option 66</summary>
        TFTPServerName = 0x42,
        /// <summary>Option 67</summary>
        BootfileName = 0x43,
        /// <summary>Option 68</summary>
        MobileIPHomeAgent = 0x44,
        /// <summary>Option 69</summary>
        SMTPServer = 0x45,
        /// <summary>Option 70</summary>
        POP3Server = 0x46,
        /// <summary>Option 71</summary>
        NNTPServer = 0x47,
        /// <summary>Option 72</summary>
        DefaultWWWServer = 0x48,
        /// <summary>Option 73</summary>
        DefaultFingerServer = 0x49,
        /// <summary>Option 74</summary>
        DefaultIRCServer = 0x4A,
        /// <summary>Option 75</summary>
        StreetTalkServer = 0x4B,
        /// <summary>Option 76</summary>
        STDAServer = 0x4C,
        /// <summary>Option 82</summary>
        RelayInfo = 0x52,
        /// <summary>Option 121</summary>
        StaticRoutes = 0x79,
        /// <summary>Option 249</summary>
        StaticRoutesWin = 0xF9,
        /// <summary>Option 252</summary>
        Wpad = 0xFC,
        /// <summary>Option 255 (END option)</summary>
        END_Option = 0xFF
    }
}
